version: '3'
services:
    redis:
        image: redis:bullseye
        volumes:
            - redis-data:/data
        ports:
            - "127.0.0.1:6379:6379"
        networks:
            - osaas
    api:
        image: osaas-server # build it from the Dockerfile in the same directory
        build: .
        volumes:
            - ./app:/app
            - node_modules:/app/node_modules
            - /var/run/docker.sock:/var/run/docker.sock # for docker-in-docker
        command: npm start
        depends_on:
            - redis
        environment:
            - NODE_ENV=development
        networks:
            - osaas
    web:
        image: osaas-server # build it from the Dockerfile in the same directory
        build: .
        volumes:
            - ./app:/app
            - node_modules:/app/node_modules
        command: npm run frontend
        networks:
            - osaas
    nginx:
        image: valian/docker-nginx-auto-ssl
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./app:/app
        environment:
            - SITES=osaas.localhost=web;api.osaas.localhost=api
            - FORCE_HTTPS=true
        networks:
            - osaas
        depends_on:
            - web
volumes:
    node_modules:
    redis-data:
networks:
    osaas:
        name: osaas


    